apiVersion: apps/v1
kind: Deployment
metadata:
  name: monero-helm-RPCManager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monero-helm-RPCManager
  template:
    metadata:
      labels:
        app: monero-helm-RPCManager
    spec:
      containers:
        - name: monero-helm-RPCManager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{ toJson .Values.command }}
          args: {{ toJson .Values.args }}
          ports:
            - containerPort: 8080
