apiVersion: apps/v1
kind: Deployment
metadata:
  name: monero-rpcmanager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: monero-RPCManager
  template:
    metadata:
      labels:
        app: monero-RPCManager
    spec:
      containers:
        - name: monero-rpcmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
