apiVersion: v1
kind: Service
metadata:
  name: monero-wallet-rpcmanager-svc
spec:
  selector:
    app: monero-wallet-rpcmanager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
